### ISSUE TITLE
ASSERTION FAILED: program->vertexShaderURL().isValid() || program->fragmentShaderURL().isValid() in WebCore::programCacheKey

### ISSUE THREAD

**Issue by renatahodovan** [WebKitNix/webkitnix#20]
The following test crashes on the above assertion:

```
<html>
   <base href="data:tex/css">
   <span style="-webkit-filter: custom(url(&apos;../resources/vertex-offset.vs&apos;))"></span>
</html>
```
# The backtrace:

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4d6a339 in WTFCrash ()
    at /home/reni/Data/REPOS/webkitnix/Source/WTF/wtf/Assertions.cpp:339
339         *(int *)(uintptr_t)0xbbadbeef = 0;
(gdb) bt
#0  0x00007ffff4d6a339 in WTFCrash ()

```
at /home/reni/Data/REPOS/webkitnix/Source/WTF/wtf/Assertions.cpp:339
```
#1  0x00007ffff3fae4c4 in WebCore::programCacheKey (program=0x810100)

```
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/rendering/style/StyleCustomFilterProgramCache.cpp:43
```
#2  0x00007ffff3fae732 in WebCore::StyleCustomFilterProgramCache::lookup (

```
this=0x80f770, program=0x810100)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/rendering/style/StyleCustomFilterProgramCache.cpp:67
```
#3  0x00007ffff35d7f21 in WebCore::StyleResolver::loadPendingShaders (

```
this=0x736d70)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/css/StyleResolver.cpp:3671
```
#4  0x00007ffff35dadcf in WebCore::StyleResolver::loadPendingResources (

```
this=0x736d70)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/css/StyleResolver.cpp:4255
```
#5  0x00007ffff35d2506 in WebCore::StyleResolver::applyMatchedProperties (

```
this=0x736d70, matchResult=..., element=0x7ca220)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/css/StyleResolver.cpp:1954
```
#6  0x00007ffff35ce8b5 in WebCore::StyleResolver::styleForElement (

```
this=0x736d70, element=0x7ca220, defaultParent=0x0, 
```

---Type <return> to continue, or q <return> to quit---
    sharingBehavior=WebCore::AllowStyleSharing, 
    matchingBehavior=WebCore::MatchAllRules, regionForStyling=0x0)
    at /home/reni/Data/REPOS/webkitnix/Source/WebCore/css/StyleResolver.cpp:1031
#7  0x00007ffff36977c6 in WebCore::Element::styleForRenderer (this=0x7ca220)

```
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/dom/Element.cpp:1545
```
#8  0x00007ffff36f11a5 in WebCore::NodeRenderingContext::createRendererForElementIfNeeded (this=0x7fffffffd1a0)

```
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/dom/NodeRenderingContext.cpp:261
```
#9  0x00007ffff3696f97 in WebCore::Element::createRendererIfNeeded (

```
this=0x7ca220, context=...)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/dom/Element.cpp:1424
```
#10 0x00007ffff3696ffb in WebCore::Element::attach (this=0x7ca220, context=...)

```
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/dom/Element.cpp:1433
```
#11 0x00007ffff38ea6e2 in WebCore::executeTask (task=...)

```
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/html/parser/HTMLConstructionSite.cpp:103
```
#12 0x00007ffff38ea9fb in WebCore::HTMLConstructionSite::executeQueuedTasks (

```
this=0x77a8f8)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/html/parser/HTMLConstructionSite.cpp:146
```
#13 0x00007ffff3911ab0 in WebCore::HTMLTreeBuilder::constructTree (

---Type <return> to continue, or q <return> to quit---
    this=0x77a8e0, token=0x7fffffffd340)
    at /home/reni/Data/REPOS/webkitnix/Source/WebCore/html/parser/HTMLTreeBuilder.cpp:382
#14 0x00007ffff38f20e0 in WebCore::HTMLDocumentParser::constructTreeFromHTMLToken (this=0x754180, rawToken=...)

```
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/html/parser/HTMLDocumentParser.cpp:594
```
#15 0x00007ffff38f1d76 in WebCore::HTMLDocumentParser::pumpTokenizer (

```
this=0x754180, mode=WebCore::HTMLDocumentParser::AllowYield)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/html/parser/HTMLDocumentParser.cpp:551
```
#16 0x00007ffff38f1543 in WebCore::HTMLDocumentParser::pumpTokenizerIfPossible

```
(this=0x754180, mode=WebCore::HTMLDocumentParser::AllowYield)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/html/parser/HTMLDocumentParser.cpp:235
```
#17 0x00007ffff38f2613 in WebCore::HTMLDocumentParser::append (this=0x754180,

```
inputSource=<incomplete type>)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/html/parser/HTMLDocumentParser.cpp:740
```
#18 0x00007ffff36370bd in WebCore::DecodedDataDocumentParser::flush (

```
this=0x754180, writer=0x754870)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/dom/DecodedDataDocumentParser.cpp:60
```

---Type <return> to continue, or q <return> to quit---
#19 0x00007ffff3a48a99 in WebCore::DocumentWriter::end (this=0x754870)

```
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/loader/DocumentWriter.cpp:245
```
#20 0x00007ffff3a37d80 in WebCore::DocumentLoader::finishedLoading (

```
this=0x7547d0, finishTime=0)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/loader/DocumentLoader.cpp:402
```
#21 0x00007ffff3a37aee in WebCore::DocumentLoader::notifyFinished (

```
this=0x7547d0, resource=0x6ceb70)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/loader/DocumentLoader.cpp:344
```
#22 0x00007ffff3ac0f2c in WebCore::CachedResource::checkNotify (this=0x6ceb70)

```
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/loader/cache/CachedResource.cpp:369
```
#23 0x00007ffff3ac1002 in WebCore::CachedResource::finishLoading (

```
this=0x6ceb70)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/loader/cache/CachedResource.cpp:385
```
#24 0x00007ffff3abdec4 in WebCore::CachedRawResource::finishLoading (

```
this=0x6ceb70, data=0x710f90)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/loader/cache/CachedRawResource.cpp:94
```
#25 0x00007ffff3a86438 in WebCore::SubresourceLoader::didFinishLoading (

---Type <return> to continue, or q <return> to quit---
    this=0x70f7c0, finishTime=0)
    at /home/reni/Data/REPOS/webkitnix/Source/WebCore/loader/SubresourceLoader.cpp:282
#26 0x00007ffff3a826cf in WebCore::ResourceLoader::didFinishLoading (

```
this=0x70f7c0, finishTime=0)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/loader/ResourceLoader.cpp:488
```
#27 0x00007ffff470c0f0 in WebCore::readCallback (asyncResult=0x85f9a0,

```
data=0x67d170)
at /home/reni/Data/REPOS/webkitnix/Source/WebCore/platform/network/soup/ResourceHandleSoup.cpp:1335
```
#28 0x00007ffff0ca102a in async_ready_callback_wrapper (

```
source_object=0x83fb60, res=0x85f9a0, user_data=0x67d170)
at ginputstream.c:530
```
#29 0x00007ffff0cc05bb in g_task_return_now (task=0x85f9a0) at gtask.c:1105
#30 0x00007ffff0cc05d9 in complete_in_idle_cb (task=0x85f9a0) at gtask.c:1114
#31 0x00007ffff0fe9f56 in g_main_dispatch (context=0x610770) at gmain.c:3054
#32 g_main_context_dispatch (context=context@entry=0x610770) at gmain.c:3630
#33 0x00007ffff0fea2a8 in g_main_context_iterate (context=0x610770,

```
block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
at gmain.c:3701
```
#34 0x00007ffff0fea6aa in g_main_loop_run (loop=0x6108d0) at gmain.c:3895
#35 0x00007ffff46b6fc2 in WebCore::RunLoop::run ()

---Type <return> to continue, or q <return> to quit---
    at /home/reni/Data/REPOS/webkitnix/Source/WebCore/platform/nix/RunLoopNix.cpp:60
#36 0x00007ffff4d1e0b2 in WebKit::WebProcessMainNix (argc=2,

```
argv=0x7fffffffdb68)
at /home/reni/Data/REPOS/webkitnix/Source/WebKit2/WebProcess/nix/WebProcessMainNix.cpp:88
```
#37 0x000000000040084d in main (argc=2, argv=0x7fffffffdb68)

```
at /home/reni/Data/REPOS/webkitnix/Source/WebKit2/nix/MainNix.cpp:30
```

**Comment by dakerfp** [comment]
I could not reproduce it on MiniBrowser.
Where did you experienced it?

**Comment by dakerfp** [comment]
Sorry, I reproduced.
